import { componentFromPiece, createComponent } from "./componentFactory.js";
import { createFurnitureModel, getDrawerComponentIds } from "./furnitureModel.js";
import { getComponentBounds } from "./spatial.js";
import { getDrawerGeometry } from "../drawerGeometry.js";

const piece = (pieces, name, occurrence = 0) => pieces.filter((item) => item.name === name)[occurrence];
const named = (pieces, name) => pieces.find((item) => item.name === name);
const orientationFor = (type, role) => type === "drawer-front" || type === "door" || type === "back" || type === "crossbar" ? "front" : type === "divider" || /side|support/i.test(role) ? "side" : "horizontal";
const physical = (components, id, type, role, item, parentId, metadata) => { if (item) { const orientation = orientationFor(type, role); components.push(componentFromPiece({ id, type, role, piece: item, parentId, orientation, metadata: { orientation, allowParentOverflow: type === "back" || type === "door" || type === "drawer-front", ...metadata } })); } };
const place = (components, id, position) => { const component = components.find((candidate) => candidate.id === id); if (!component) return; component.position = position; component.bounds = getComponentBounds(component); };
const finish = (furnitureType, input, components) => createFurnitureModel({ furnitureType, dimensions: input, components, generatedPieces: input.generatedPieces });

export function adaptNightstandToFurnitureModel(input) {
  const { generatedPieces: pieces, structure } = input; const c = [];
  physical(c, "nightstand.top", "panel", "top", named(pieces, "Tapa superior"), "nightstand.root");
  [0, 1].forEach((index) => physical(c, `nightstand.${index ? "rightSide" : "leftSide"}`, "panel", index ? "right-side" : "left-side", piece(pieces, "Laterales", index), "nightstand.root"));
  physical(c, "nightstand.back", "back", "back", named(pieces, "Fondo de cartón prensado"), "nightstand.root");
  physical(c, "nightstand.frontCrossbar", "crossbar", "front-crossbar", named(pieces, "Travesaño frontal inferior"), "nightstand.root");
  physical(c, "nightstand.rearCrossbar", "crossbar", "rear-crossbar", named(pieces, "Travesaño trasero inferior"), "nightstand.root");
  (structure?.drawerFrontHeightsCm ?? []).forEach((height, index) => {
    const parentId = `nightstand.drawer.${index + 1}`; const ids = getDrawerComponentIds(parentId); c.push(createComponent({ id: parentId, type: "drawer", role: "drawer", parentId: "nightstand.root", dimensions: { widthCm: structure.drawerFrontWidthCm, heightCm: height, depthCm: structure.drawerGeometry?.drawerLayouts[index]?.depthCm ?? 0 }, metadata: { semanticId: parentId } }));
    physical(c, ids.front, "drawer-front", "front", piece(pieces, "Frente de cajón", index), parentId);
    [[ids.leftSide, "Lateral izquierdo de cajón", "left-side"], [ids.rightSide, "Lateral derecho de cajón", "right-side"], [ids.back, "Parte trasera de cajón", "back"], [ids.bottom, "Base de cartón prensado del cajón", "bottom"]].forEach(([id, name, role]) => physical(c, id, "panel", role, piece(pieces, name, index), parentId));
  });
  const thickness = named(pieces, "Tapa superior")?.material?.thicknessMm / 10; const backThickness = (named(pieces, "Fondo de cartón prensado")?.material?.thicknessMm ?? 0) / 10;
  place(c, "nightstand.top", { xCm: 0, yCm: input.heightCm / 2 - thickness / 2, zCm: thickness / 2 }); c.find((x) => x.id === "nightstand.top").metadata.allowParentOverflow = true; place(c, "nightstand.leftSide", { xCm: -input.widthCm / 2 + thickness / 2, yCm: -thickness / 2, zCm: 0 }); place(c, "nightstand.rightSide", { xCm: input.widthCm / 2 - thickness / 2, yCm: -thickness / 2, zCm: 0 }); place(c, "nightstand.back", { xCm: 0, yCm: 0, zCm: -input.depthCm / 2 - backThickness / 2 }); place(c, "nightstand.frontCrossbar", { xCm: 0, yCm: -input.heightCm / 2 + structure.frontHeightCm / 2, zCm: input.depthCm / 2 - thickness / 2 }); place(c, "nightstand.rearCrossbar", { xCm: 0, yCm: -input.heightCm / 2 + structure.rearHeightCm / 2, zCm: -input.depthCm / 2 + thickness / 2 });
  (structure.drawerGeometry?.drawerLayouts ?? []).forEach((layout, index) => { const id = `nightstand.drawer.${index + 1}`; const left = piece(pieces, "Lateral izquierdo de cajón", index); const back = piece(pieces, "Parte trasera de cajón", index); const bottom = piece(pieces, "Base de cartón prensado del cajón", index); const front = piece(pieces, "Frente de cajón", index); const drawer = c.find((x) => x.id === id); const depth = left?.length ?? 0; const boxWidth = (back?.length ?? 0) + thickness * 2; const centerZ = input.depthCm / 2 - depth / 2; const geometry = getDrawerGeometry({ centerZ, boxWidthCm: boxWidth, drawerHeightCm: layout.physicalHeightCm, sideDepthCm: depth, sideHeightCm: left?.width ?? layout.sideHeightCm, thicknessCm: thickness, bottomThicknessCm: (bottom?.material?.thicknessMm ?? 0) / 10, frontWidthCm: front?.length ?? structure.drawerFrontWidthCm, frontHeightCm: front?.width ?? layout.frontHeightCm, backWidthCm: back?.length ?? 0, backHeightCm: back?.width ?? 0, bottomWidthCm: bottom?.length ?? 0, bottomDepthCm: bottom?.width ?? 0, frontCenterYCm: layout.frontCenterYCm, structureCenterYCm: layout.structureCenterYCm, bottomCenterYCm: layout.bottomCenterYCm }); [["front", geometry.front], ["left-side", geometry.leftSide], ["right-side", geometry.rightSide], ["back", geometry.back], ["bottom", geometry.bottom]].forEach(([role, part]) => { const component = c.find((x) => x.id === `${id}.${role}`); if (component) { component.position = part.position; component.orientation = part.orientation; component.bounds = getComponentBounds(component); component.metadata.allowParentOverflow = true; } }); if (drawer) { drawer.position = geometry.envelope.position; drawer.bounds = getComponentBounds(drawer); } }); return finish("nightstand", input, c);
}

export function adaptDeskToFurnitureModel(input) {
  const { generatedPieces: pieces, structure } = input; const c = []; const root = "desk.root";
  physical(c, "desk.top", "panel", "top", named(pieces, "Tapa superior"), root); ["izquierdo", "derecho"].forEach((side) => physical(c, `desk.${side === "izquierdo" ? "leftSide" : "rightSide"}`, "panel", `${side === "izquierdo" ? "left" : "right"}-side`, named(pieces, `Lateral ${side}`), root));
  const moduleId = "desk.drawerModule"; c.push(createComponent({ id: moduleId, type: "section", role: "drawer-module", parentId: root, dimensions: { widthCm: structure.moduleWidthCm, heightCm: input.heightCm, depthCm: input.depthCm }, position: { xCm: structure.moduleCenterXCm, yCm: 0, zCm: 0 } }));
  c.push(createComponent({ id: "desk.legOpening", type: "opening", role: "leg-opening", parentId: root, dimensions: { widthCm: structure.legroomWidthCm, heightCm: structure.legHeightCm, depthCm: input.depthCm }, position: { xCm: structure.sectionGeometry?.freeOpeningCenterXCm ?? null, yCm: 0, zCm: 0 } }));
  physical(c, "desk.divider", "divider", "drawer-module-divider", named(pieces, "Divisor módulo de cajones"), root); physical(c, "desk.rearCrossbar", "crossbar", "rear-crossbar", named(pieces, "Travesaño trasero"), root);
  for (let i = 0; i < input.drawers; i += 1) { const id = `desk.drawer.${i + 1}`; const ids = getDrawerComponentIds(id); c.push(createComponent({ id, type: "drawer", role: "drawer", parentId: moduleId, dimensions: { widthCm: structure.drawerOpeningWidthCm, heightCm: structure.drawerSideHeightCm, depthCm: structure.drawerDepthCm } })); physical(c, ids.front, "drawer-front", "front", named(pieces, ["Frente cajón superior", "Frente cajón central", "Frente cajón inferior"][i] ?? `Frente cajón ${i + 1}`), id); [[ids.leftSide, "Lateral izquierdo de cajón", "left-side"], [ids.rightSide, "Lateral derecho de cajón", "right-side"], [ids.back, "Parte trasera de cajón", "back"], [ids.bottom, "Base de cartón prensado del cajón", "bottom"]].forEach(([childId, name, role]) => physical(c, childId, "panel", role, piece(pieces, name, i), id)); }
  const thickness = named(pieces, "Tapa superior")?.material?.thicknessMm / 10; place(c, "desk.top", { xCm: 0, yCm: input.heightCm / 2 - thickness / 2, zCm: 0 }); place(c, "desk.leftSide", { xCm: -input.widthCm / 2 + thickness / 2, yCm: -thickness / 2, zCm: 0 }); place(c, "desk.rightSide", { xCm: input.widthCm / 2 - thickness / 2, yCm: -thickness / 2, zCm: 0 }); place(c, "desk.divider", { xCm: structure.dividerCenterXCm, yCm: -thickness / 2, zCm: thickness / 2 }); place(c, "desk.rearCrossbar", { xCm: 0, yCm: input.heightCm / 2 - thickness - structure.rearCrossbarHeightCm / 2, zCm: -input.depthCm / 2 + thickness / 2 }); (structure.drawerLayouts ?? []).forEach((layout, i) => { const id = `desk.drawer.${i + 1}`; place(c, id, { xCm: structure.moduleCenterXCm, yCm: layout.structureCenterYCm, zCm: input.depthCm / 2 - structure.drawerDepthCm / 2 }); place(c, `${id}.front`, { xCm: structure.moduleCenterXCm, yCm: layout.frontCenterYCm, zCm: input.depthCm / 2 + thickness / 2 }); });
  return finish("desk", input, c);
}

export function adaptTvStandToFurnitureModel(input) {
  const { generatedPieces: pieces, structure } = input; const c = []; const root = "tvStand.root";
  ["top", "leftSide", "rightSide", "back"].forEach((id, i) => physical(c, `tvStand.${id}`, id === "back" ? "back" : "panel", id.replace(/[A-Z]/g, (v) => `-${v.toLowerCase()}`), named(pieces, ["Tapa superior", "Lateral izquierdo", "Lateral derecho", "Fondo trasero completo"][i]), root));
  (structure.sectionWidthsCm ?? []).forEach((width, i) => c.push(createComponent({ id: `tvStand.section.${i + 1}`, type: "section", role: "section", parentId: root, dimensions: { widthCm: width, heightCm: input.heightCm, depthCm: input.depthCm }, position: { xCm: structure.sectionCentersXCm?.[i] ?? null, yCm: 0, zCm: 0 } })));
  physical(c, "tvStand.divider.1", "divider", "vertical-divider", named(pieces, "Divisor vertical central"), root); ["izquierda", "derecha"].forEach((side, i) => physical(c, `tvStand.shelf.${i + 1}`, "shelf", "shelf", named(pieces, `Repisa ${side}`), `tvStand.section.${i + 1}`));
  ["izquierdo", "derecho"].forEach((side, i) => physical(c, `tvStand.support.${i + 1}`, "panel", "vertical-support", named(pieces, `Soporte vertical ${side}`), `tvStand.section.${i + 1}`));
  ["superior", "inferior"].forEach((side) => physical(c, `tvStand.rearCrossbar.${side}`, "crossbar", "rear-crossbar", named(pieces, `Travesaño trasero ${side}`), root));
  const thickness = named(pieces, "Tapa superior")?.material?.thicknessMm / 10;
  place(c, "tvStand.top", { xCm: 0, yCm: input.heightCm / 2 - thickness / 2, zCm: 0 }); place(c, "tvStand.leftSide", { xCm: -input.widthCm / 2 + thickness / 2, yCm: -thickness / 2, zCm: 0 }); place(c, "tvStand.rightSide", { xCm: input.widthCm / 2 - thickness / 2, yCm: -thickness / 2, zCm: 0 }); place(c, "tvStand.back", { xCm: 0, yCm: 0, zCm: -input.depthCm / 2 - (named(pieces, "Fondo trasero completo")?.material?.thicknessMm ?? 0) / 20 });
  place(c, "tvStand.divider.1", { xCm: structure.dividerCenterXCm, yCm: 0, zCm: thickness / 2 }); (structure.sectionCentersXCm ?? []).forEach((x, i) => { place(c, `tvStand.shelf.${i + 1}`, { xCm: x, yCm: structure.shelfCenterYCm, zCm: thickness / 2 }); place(c, `tvStand.support.${i + 1}`, { xCm: structure.supportCentersXCm?.[i], yCm: -input.heightCm / 2 + thickness + structure.supportHeightCm / 2, zCm: thickness / 2 }); });
  place(c, "tvStand.rearCrossbar.superior", { xCm: 0, yCm: input.heightCm / 2 - thickness - structure.upperRearHeightCm / 2, zCm: -input.depthCm / 2 + thickness / 2 }); place(c, "tvStand.rearCrossbar.inferior", { xCm: 0, yCm: -input.heightCm / 2 + thickness + structure.lowerRearHeightCm / 2, zCm: -input.depthCm / 2 + thickness / 2 }); return finish("tvStand", input, c);
}

export function adaptCatHouseToFurnitureModel(input) { const { generatedPieces: pieces } = input; const c = []; const root = "catHouse.root"; [["top", "Tapa superior"], ["bottom", "Base inferior"], ["leftSide", "Lateral izquierdo"], ["rightSide", "Lateral derecho"], ["back", "Trasera de cartón prensado"]].forEach(([id, name]) => physical(c, `catHouse.${id}`, id === "back" ? "back" : "panel", id, named(pieces, name), root)); const thickness = (named(pieces, "Lateral izquierdo")?.material?.thicknessMm ?? 0) / 10; place(c, "catHouse.top", { xCm: 0, yCm: input.heightCm / 2 - thickness / 2, zCm: 0 }); place(c, "catHouse.bottom", { xCm: 0, yCm: -input.heightCm / 2 + thickness / 2, zCm: 0 }); place(c, "catHouse.leftSide", { xCm: -input.widthCm / 2 + thickness / 2, yCm: 0, zCm: 0 }); place(c, "catHouse.rightSide", { xCm: input.widthCm / 2 - thickness / 2, yCm: 0, zCm: 0 }); place(c, "catHouse.back", { xCm: 0, yCm: 0, zCm: -input.depthCm / 2 - (named(pieces, "Trasera de cartón prensado")?.material?.thicknessMm ?? 0) / 20 }); c.push(createComponent({ id: "catHouse.frontOpening", type: "opening", role: "front-opening", parentId: root, dimensions: { widthCm: input.widthCm - thickness * 2, heightCm: input.heightCm - thickness * 2, depthCm: 0 }, position: { xCm: 0, yCm: 0, zCm: input.depthCm / 2 } })); return finish("catHouse", input, c); }

export function adaptWardrobeToFurnitureModel(input) {
  const { generatedPieces: pieces, structure } = input; const c = []; const root = "wardrobe.root";
  physical(c, "wardrobe.top", "panel", "top", named(pieces, structure.isSlidingDoors ? "Tapa superior extendida" : "Tapa superior"), root); ["izquierdo", "derecho"].forEach((side) => physical(c, `wardrobe.${side === "izquierdo" ? "leftSide" : "rightSide"}`, "panel", `${side === "izquierdo" ? "left" : "right"}-side`, named(pieces, `Lateral ${side}`), root));
  (structure.sectionWidthsCm ?? []).forEach((width, i) => { const body = i + 1; const id = `wardrobe.body.${body}`; c.push(createComponent({ id, type: "section", role: "body", parentId: root, dimensions: { widthCm: width, heightCm: input.heightCm, depthCm: input.depthCm }, position: { xCm: structure.bodyCentersXCm?.[i] ?? null, yCm: 0, zCm: 0 } })); physical(c, `${id}.back`, "back", "back", named(pieces, `Fondo cartón prensado Cuerpo ${body}`), id); ["superior", "principal"].forEach((kind) => physical(c, `${id}.door.${kind}`, "door", kind, named(pieces, `Puerta ${kind} Cuerpo ${body}`), id, { orientation: "front" })); if (structure.isSlidingDoors) physical(c, `${id}.door`, "door", "sliding", named(pieces, `Puerta corrediza ${body}`), id, { orientation: "sliding" }); });
  [1, 2].forEach((n) => physical(c, `wardrobe.divider.${n}`, "divider", "vertical-divider", named(pieces, `Divisor vertical Cuerpo ${n} / Cuerpo ${n + 1}`), root));
  (structure.sectionWidthsCm ?? []).forEach((width, i) => { const body = i + 1; const parentId = `wardrobe.body.${body}`; ["frontal", "trasero"].forEach((side) => physical(c, `${parentId}.lowerCrossbar.${side}`, "crossbar", `lower-${side}-crossbar`, named(pieces, `Travesaño ${side} inferior Cuerpo ${body}`), parentId)); physical(c, `${parentId}.upperShelf`, "shelf", "upper-shelf", named(pieces, `Repisa superior Cuerpo ${body}`), parentId); });
  ["sobre cajones Cuerpo 1", "intermedia 1 Cuerpo 1", "intermedia 2 Cuerpo 1", "sobre cajones Cuerpo 3", "inferior zapatero Cuerpo 2"].forEach((suffix, index) => { const body = suffix.endsWith("1") ? 1 : suffix.endsWith("3") ? 3 : 2; physical(c, `wardrobe.body.${body}.shelf.fixed.${index + 1}`, "shelf", "shelf", named(pieces, `Repisa ${suffix}`), `wardrobe.body.${body}`); });
  for (let shelf = 1; shelf <= input.shelves; shelf += 1) physical(c, `wardrobe.body.2.shoeShelf.${shelf}`, "shelf", "shoe-shelf", named(pieces, `Repisa zapatos ${shelf} Cuerpo 2`), "wardrobe.body.2");
  [1, 2, 3].forEach((body) => c.push(createComponent({ id: `wardrobe.body.${body}.opening`, type: "opening", role: body === 2 ? "hanging-opening" : "storage-opening", parentId: `wardrobe.body.${body}`, dimensions: { widthCm: structure.sectionWidthsCm?.[body - 1] ?? 0, heightCm: input.heightCm, depthCm: input.depthCm }, position: null })));
  (structure.drawerLayouts ?? []).forEach((layout) => { const body = layout.bodyIndex + 1; const number = layout.drawerIndex + 1; const id = `wardrobe.body.${body}.drawer.${number}`; const ids = getDrawerComponentIds(id); c.push(createComponent({ id, type: "drawer", role: "drawer", parentId: `wardrobe.body.${body}`, dimensions: { widthCm: layout.drawerBoxWidthCm, heightCm: structure.drawerSideHeightCm, depthCm: structure.drawerDepthCm } })); physical(c, ids.front, "drawer-front", "front", named(pieces, `Frente Cajón ${number} Cuerpo ${body}`), id); [[ids.leftSide, "Lateral izquierdo", "left-side"], [ids.rightSide, "Lateral derecho", "right-side"], [ids.back, "Parte trasera", "back"], [ids.bottom, "Base cartón prensado", "bottom"]].forEach(([childId, prefix, role]) => physical(c, childId, "panel", role, named(pieces, `${prefix} Cajón ${number} Cuerpo ${body}`), id)); });
  const thickness = named(pieces, structure.isSlidingDoors ? "Tapa superior extendida" : "Tapa superior")?.material?.thicknessMm / 10; const hardboardThickness = (named(pieces, "Fondo cartón prensado Cuerpo 1")?.material?.thicknessMm ?? 0) / 10;
  place(c, "wardrobe.top", { xCm: 0, yCm: input.heightCm / 2 - thickness / 2, zCm: structure.isSlidingDoors ? structure.slidingDoorExtensionCm / 2 : 0 }); c.find((x) => x.id === "wardrobe.top").metadata.allowParentOverflow = Boolean(structure.isSlidingDoors); place(c, "wardrobe.leftSide", { xCm: structure.panelCentersXCm[0], yCm: -thickness / 2, zCm: 0 }); place(c, "wardrobe.rightSide", { xCm: structure.panelCentersXCm.at(-1), yCm: -thickness / 2, zCm: 0 }); [1, 2].forEach((n) => place(c, `wardrobe.divider.${n}`, { xCm: structure.dividerPositionsCm[n - 1], yCm: -thickness / 2, zCm: 0 }));
  (structure.sectionWidthsCm ?? []).forEach((width, i) => { const body = i + 1; const x = structure.bodyCentersXCm[i]; place(c, `wardrobe.body.${body}.back`, { xCm: structure.backLayouts[i].centerXCm, yCm: 0, zCm: -input.depthCm / 2 - hardboardThickness / 2 }); place(c, `wardrobe.body.${body}.upperShelf`, { xCm: x, yCm: structure.upperShelfYCm, zCm: 0 }); ["frontal", "trasero"].forEach((side) => place(c, `wardrobe.body.${body}.lowerCrossbar.${side}`, { xCm: x, yCm: -input.heightCm / 2 + structure.lowerCrossbarHeightCm / 2, zCm: side === "frontal" ? input.depthCm / 2 - thickness / 2 : -input.depthCm / 2 + thickness / 2 })); ["superior", "principal"].forEach((kind) => { const y = kind === "superior" ? structure.upperDoorCenterYCm : structure.mainDoorCentersYCm[i]; place(c, `wardrobe.body.${body}.door.${kind}`, { xCm: x, yCm: y, zCm: input.depthCm / 2 + thickness / 2 }); }); if (structure.isSlidingDoors) place(c, `wardrobe.body.${body}.door`, { xCm: structure.slidingDoorClosedCentersXCm[i], yCm: (structure.slidingLowerSupportHeightCm - thickness) / 2, zCm: input.depthCm / 2 + structure.slidingDoorExtensionCm - thickness * (i % structure.slidingTrackCount + 1) }); });
  place(c, "wardrobe.body.1.shelf.fixed.1", { xCm: structure.bodyCentersXCm[0], yCm: structure.drawerShelfYCm, zCm: 0 }); place(c, "wardrobe.body.1.shelf.fixed.2", { xCm: structure.bodyCentersXCm[0], yCm: structure.intermediateShelfYCentersCm[0], zCm: 0 }); place(c, "wardrobe.body.1.shelf.fixed.3", { xCm: structure.bodyCentersXCm[0], yCm: structure.intermediateShelfYCentersCm[1], zCm: 0 }); place(c, "wardrobe.body.3.shelf.fixed.4", { xCm: structure.bodyCentersXCm[2], yCm: structure.drawerShelfYCm, zCm: 0 }); place(c, "wardrobe.body.2.shelf.fixed.5", { xCm: structure.bodyCentersXCm[1], yCm: structure.shoeBottomShelfYCm, zCm: 0 }); (structure.shoeShelfYCentersCm ?? []).forEach((y, i) => place(c, `wardrobe.body.2.shoeShelf.${i + 1}`, { xCm: structure.bodyCentersXCm[1], yCm: y, zCm: 0 }));
  (structure.drawerLayouts ?? []).forEach((layout) => { const id = `wardrobe.body.${layout.bodyIndex + 1}.drawer.${layout.drawerIndex + 1}`; place(c, id, { xCm: layout.centerXCm, yCm: layout.centerYCm, zCm: input.depthCm / 2 - structure.drawerDepthCm / 2 }); place(c, `${id}.front`, { xCm: layout.centerXCm, yCm: layout.centerYCm, zCm: input.depthCm / 2 + thickness / 2 }); });
  return finish("wardrobe", input, c);
}
