/** FurnitureModel is a read-only structural projection; existing generators remain authoritative. */
export * from "./componentTypes.js";
export * from "./componentFactory.js";
export * from "./componentValidation.js";
export * from "./furnitureModel.js";
export * from "./adapters.js";
export * from "./buildFurnitureModel.js";
export * from "./inspectorData.js";
export * from "./spatial.js";
export * from "./relationTypes.js";
export * from "./relations.js";
export * from "./relationValidation.js";
export * from "./diagnosticTypes.js";
export * from "./diagnostics.js";
export * from "./diagnosticValidation.js";
export * from "./regionTypes.js";
export * from "./regions.js";
export * from "./regionValidation.js";
export * from "./editableProperties.js";
export * from "./editAdapter.js";
export { applyFurnitureModelTransaction } from "./editTransaction.js";
