import Drawer from "./Drawer";
import { calculateBackPanelDimensions } from "../utils/backPanel";
const WOOD = "#8b5a2b"; const TOP = "#b07d4f"; const HARDBOARD = "#b98b5d";
export default function Desk({ width, height, depth, drawers, thickness = .015, backThickness = .003, drawerDimensions }) {
  const legWidth = .08;
  const columnWidth = Math.min(width * .3, .48); const usableHeight = height - thickness;
  const drawerHeight = drawers ? Math.min(.22, (usableHeight - .08) / drawers) : 0; const drawerDepth = depth * .78;
  const backPanel = calculateBackPanelDimensions({ externalWidth: width, externalHeight: height, panelThickness: thickness, backPanelThickness: backThickness, hasTop: true, hasBottom: false, furnitureDepth: depth });
  return <group><mesh position={[0, height / 2 - thickness / 2, 0]}><boxGeometry args={[width, thickness, depth]} /><meshStandardMaterial color={TOP} /></mesh>{[-1, 1].map((side) => <mesh key={side} position={[side * (width / 2 - legWidth / 2), 0, 0]}><boxGeometry args={[legWidth, usableHeight, depth]} /><meshStandardMaterial color={WOOD} /></mesh>)}<mesh position={[0, height / 2 - .16, -depth / 2 + thickness / 2]}><boxGeometry args={[width - legWidth * 2, .22, thickness]} /><meshStandardMaterial color={WOOD} /></mesh><mesh position={[0, 0, backPanel.centerZ]}><boxGeometry args={[backPanel.width, backPanel.height, backPanel.thickness]} /><meshStandardMaterial color={HARDBOARD} /></mesh>{drawers > 0 && drawerDimensions.hasEnoughDepth && <group position={[width / 2 - legWidth - columnWidth / 2, -thickness / 2, 0]}>{[-1, 1].map((side) => <mesh key={side} position={[side * (columnWidth / 2 - thickness / 2), 0, 0]}><boxGeometry args={[thickness, usableHeight, drawerDepth]} /><meshStandardMaterial color={WOOD} /></mesh>)}{Array.from({ length: drawers }).map((_, index) => <Drawer key={index} width={drawerDimensions.externalWidthCm / 100} height={drawerHeight - .015} depth={drawerDimensions.sideLengthCm / 100} thickness={thickness} baseThickness={backThickness} position={[0, usableHeight / 2 - drawerHeight / 2 - .04 - index * drawerHeight, 0]} />)}</group>}</group>;
}
