import { useMemo, useState } from "react";
import { buildComponentTree, filterComponents, getAncestorIds, getDiagnosticsForComponent, getHighlightedComponentIds, getRegionHeight, getRegionsForComponent, getRegionWidth, getRelationsForComponent, resolveSourcePieces, summarizeFurnitureDiagnostics, summarizeFurnitureModel } from "../utils/furnitureModel";
import { REGION_FILTERS } from "../utils/furnitureRegionOverlay.js";

const FILTERS = ["all", "panel", "shelf", "divider", "drawer", "door", "opening", "section"];
function TreeNode({ node, allowedIds, selectedId, onSelect, expandedIds, onToggle, depth = 0 }) { const { component, children } = node; if (!allowedIds.has(component.id)) return children.map((child) => <TreeNode key={child.component.id} node={child} allowedIds={allowedIds} selectedId={selectedId} onSelect={onSelect} expandedIds={expandedIds} onToggle={onToggle} depth={depth} />); const expanded = expandedIds.has(component.id); return <div>{children.length > 0 && <button type="button" aria-label={`${expanded ? "Collapse" : "Expand"} ${component.id}`} onClick={() => onToggle(component.id)}>{expanded ? "▾" : "▸"}</button>}<button type="button" className={selectedId === component.id ? "fm-selected" : ""} style={{ marginLeft: `${depth * 12}px` }} onClick={() => onSelect(component.id)}>{component.id} <small>[{component.type}]</small></button>{expanded && children.map((child) => <TreeNode key={child.component.id} node={child} allowedIds={allowedIds} selectedId={selectedId} onSelect={onSelect} expandedIds={expandedIds} onToggle={onToggle} depth={depth + 1} />)}</div>; }

export default function FurnitureModelInspector({ model, generatedPieces, selectedId, onSelectComponent, showRegions, onShowRegionsChange, showRegionDimensions, onShowRegionDimensionsChange, regionFilter, onRegionFilterChange, selectedRegionId, onSelectRegion }) {
  const [open, setOpen] = useState(false); const [type, setType] = useState("all"); const [search, setSearch] = useState(""); const [diagnosticSeverity, setDiagnosticSeverity] = useState("all"); const [showJson, setShowJson] = useState(false); const [expandedIds, setExpandedIds] = useState(() => new Set([`${model.furnitureType}.root`]));
  const tree = useMemo(() => buildComponentTree(model), [model]); const summary = useMemo(() => summarizeFurnitureModel(model), [model]); const diagnosticSummary = useMemo(() => summarizeFurnitureDiagnostics(model), [model]); const matches = useMemo(() => filterComponents(model, type, search), [model, type, search]); const selected = model.components.find((c) => c.id === selectedId) ?? null; const highlightedCount = useMemo(() => getHighlightedComponentIds(model, selectedId).size, [model, selectedId]); const selectedRelations = useMemo(() => getRelationsForComponent(model, selectedId), [model, selectedId]); const selectedRegions = useMemo(() => getRegionsForComponent(model, selectedId), [model, selectedId]); const selectedDiagnostics = useMemo(() => getDiagnosticsForComponent(model, selectedId).filter(({ severity }) => diagnosticSeverity === "all" || severity === diagnosticSeverity), [diagnosticSeverity, model, selectedId]); const renderedExpandedIds = useMemo(() => new Set([...expandedIds, ...getAncestorIds(model, selectedId)]), [expandedIds, model, selectedId]); const toggle = (id) => setExpandedIds((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const inspectorOpen = open || Boolean(selectedId);
  return <details className="furniture-model-inspector" open={inspectorOpen} onToggle={(event) => setOpen(event.currentTarget.open)}><summary>FurnitureModel Inspector · {model.validation.valid ? "Valid" : `${model.validation.errors.length} errors`}</summary>{inspectorOpen && <div>
    <p>Components: {summary.components} · Physical: {summary.physical} · Logical: {summary.logical} · Sections: {summary.sections} · Drawers: {summary.drawers} · Doors: {summary.doors} · Openings: {summary.openings} · Front regions: {model.regions?.length ?? 0}</p><p>Position: {summary.positioned}/{summary.components} · Bounds: {summary.bounded}/{summary.components} · Orientation: {summary.oriented}/{summary.components} · Source pieces: {summary.sourced}/{summary.components}</p><div className="fm-region-controls"><label><input type="checkbox" checked={showRegions} onChange={(event) => onShowRegionsChange?.(event.target.checked)} /> Show regions</label>{showRegions && <><label><input type="checkbox" checked={showRegionDimensions} onChange={(event) => onShowRegionDimensionsChange?.(event.target.checked)} /> Show dimensions</label><label>Region role <select value={regionFilter} onChange={(event) => onRegionFilterChange?.(event.target.value)}>{REGION_FILTERS.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><button type="button" disabled={!selectedRegionId} onClick={() => onSelectRegion?.(null)}>Clear region selection</button><small>Regions stay in their nominal closed structural position; physical highlights follow the current mesh.</small></>}</div><p>Diagnostics · Errors: {diagnosticSummary.errors} · Warnings: {diagnosticSummary.warnings} · Info: {diagnosticSummary.info} · <label>Show <select value={diagnosticSeverity} onChange={(event) => setDiagnosticSeverity(event.target.value)}><option value="all">All</option><option value="error">Errors</option><option value="warning">Warnings</option><option value="info">Info</option></select></label></p>
    {!model.validation.valid && <ul>{model.validation.errors.map((error) => <li key={error}>{error}</li>)}</ul>}
    <label>Filter <select value={type} onChange={(event) => setType(event.target.value)}>{FILTERS.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label> Search <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="id, role, type" /></label>
    <button type="button" onClick={() => onSelectComponent?.(null)}>Clear selection</button>{selected && <p>Selected: {selected.id}{["drawer", "section", "opening"].includes(selected.type) ? ` · Highlighting ${highlightedCount} physical descendants` : ""}</p>}<div className="fm-tree">{tree.map((node) => <TreeNode key={node.component.id} node={node} allowedIds={new Set(matches.map((c) => c.id))} selectedId={selectedId} onSelect={onSelectComponent} expandedIds={renderedExpandedIds} onToggle={toggle} />)}</div>
    {selected && <div className="fm-details"><h3>{selected.id}</h3><pre>{JSON.stringify(selected, null, 2)}</pre>{resolveSourcePieces(selected, generatedPieces).map((piece) => <pre key={piece.id}>{JSON.stringify({ id: piece.id, name: piece.name, material: piece.material?.id, dimensions: { length: piece.length, width: piece.width }, grainRequired: piece.grainRequired, edgeBanding: piece.edgeBanding }, null, 2)}</pre>)}<h4>Regions ({selectedRegions.length})</h4>{selectedRegions.length === 0 ? <p>None</p> : selectedRegions.map((region) => <div key={region.id} className={selectedRegionId === region.id ? "fm-region-selected" : ""}><button type="button" onClick={() => onSelectRegion?.(region.id)}>{region.role} · {getRegionWidth(region)?.toFixed(2)} × {getRegionHeight(region)?.toFixed(2)} cm · {region.plane}/{region.region.axis}</button><pre>{JSON.stringify(region, null, 2)}</pre></div>)}<h4>Relations ({selectedRelations.length})</h4>{selectedRelations.length === 0 ? <p>None</p> : <ul>{selectedRelations.map((relation) => { const outgoing = relation.sourceId === selected.id; const relatedId = outgoing ? relation.targetId : relation.sourceId; return <li key={relation.id}>{outgoing ? `${relation.type} → ` : `← ${relation.type} · `}<button type="button" onClick={() => onSelectComponent?.(relatedId)}>{relatedId}</button></li>; })}</ul>}<h4>Diagnostics ({selectedDiagnostics.length})</h4>{selectedDiagnostics.length === 0 ? <p>None</p> : <ul>{selectedDiagnostics.map((diagnostic) => <li key={diagnostic.id}>[{diagnostic.severity}] {diagnostic.message}{diagnostic.relatedComponentIds.map((id) => <span key={id}> · <button type="button" onClick={() => onSelectComponent?.(id)}>{id}</button></span>)}</li>)}</ul>}</div>}
    <button type="button" onClick={() => setShowJson((value) => !value)}>{showJson ? "Ocultar JSON" : "Mostrar JSON"}</button>{showJson && <pre>{JSON.stringify({ furnitureType: model.furnitureType, modelVersion: model.modelVersion, dimensions: model.dimensions, components: model.components, regions: model.regions, relations: model.relations, diagnostics: model.diagnostics }, null, 2)}</pre>}
  </div>}</details>;
}
